version: '3'
services:
  equilibre-ve-api-subgraph-ipfs-node-1:
    image: ipfs/go-ipfs:v0.12.0
    command: /sbin/tini -- /usr/local/bin/start_ipfs.sh
    ports:
      - 5001:5001
      - 4001:4001
      - 8081:8081
    volumes:
      - ipfs-data:/data/ipfs

  equilibre-ve-api-subgraph-graph-node-1:
    build: ./graph-node
    ports:
      - 8000:8000
    environment:
      - IPFS_URL=http://equilibre-ve-api-subgraph-ipfs-node-1:5001
      - GRAPH_NODE_SUBGRAPH_VERSION=1

volumes:
  ipfs-data:
    driver: local
